from __future__ import annotations

from collections.abc import Callable, Collection, Iterator
from pathlib import Path

import numpy as np
import pandas as pd

from .data_contract import normalize_daily_bars
from .event_study import EVENT_COLUMNS, measure_events
from .signals import build_signal_variants
from .tdx_day import is_target_mainboard_path, read_tdx_day_file


ProgressCallback = Callable[[int, int], None]


def _normalize_code_filter(code_filter: Collection[str] | None) -> set[str] | None:
    if code_filter is None:
        return None
    return {str(code).strip().zfill(6) for code in code_filter if str(code).strip()}


def _path_code(path: Path) -> str | None:
    stem = path.stem.lower()
    if len(stem) != 8 or stem[:2] not in {"sh", "sz", "bj"}:
        return None
    code = stem[2:]
    return code if len(code) == 6 and code.isdigit() else None


def _expected_market_prefix(code: str) -> str | None:
    if code.startswith(("600", "601", "603", "605", "688")):
        return "sh"
    if code.startswith(("000", "001", "002", "003", "300", "301")):
        return "sz"
    if code.startswith(("4", "8", "9")):
        return "bj"
    return None


def _is_selected_tdx_path(path: Path, code_filter: set[str] | None) -> bool:
    if code_filter is None:
        return is_target_mainboard_path(path)
    if path.suffix.lower() != ".day":
        return False
    code = _path_code(path)
    if code is None or code not in code_filter:
        return False
    expected_prefix = _expected_market_prefix(code)
    return expected_prefix is None or path.stem[:2].lower() == expected_prefix



def count_tdx_mainboard_files(source_root: Path, code_filter: Collection[str] | None = None) -> int:
    """Count target mainboard TDX files for progress reporting."""
    normalized_filter = _normalize_code_filter(code_filter)
    return sum(1 for path in source_root.rglob("*.day") if _is_selected_tdx_path(path, normalized_filter))


def iter_tdx_mainboard_bars(
    source_root: Path,
    start: pd.Timestamp,
    end: pd.Timestamp,
    progress_callback: ProgressCallback | None = None,
    code_filter: Collection[str] | None = None,
) -> Iterator[pd.DataFrame]:
    """Yield one normalized technical-only frame per selected local TDX file."""
    warmup_start = start - pd.offsets.BDay(180)
    normalized_filter = _normalize_code_filter(code_filter)
    scanned_count = 0
    yielded_count = 0
    for path in sorted(source_root.rglob("*.day")):
        if not _is_selected_tdx_path(path, normalized_filter):
            continue
        scanned_count += 1
        bars = read_tdx_day_file(path).assign(
            name=lambda frame: frame["code"],
            market_cap=0,
            is_st=False,
            is_suspended=False,
        )
        bars = normalize_daily_bars(bars, require_core_pool=False)
        window = bars.loc[bars["date"].between(warmup_start, end)].copy()
        if not window.empty:
            yielded_count += 1
        if progress_callback is not None:
            progress_callback(scanned_count, yielded_count)
        if window.empty:
            continue
        yield window


def _qfq_csv_paths(source: Path) -> list[Path]:
    if source.is_file():
        return [source]
    return sorted(source.rglob("*.csv"))


def count_qfq_csv_files(source: Path, code_filter: Collection[str] | None = None) -> int:
    normalized_filter = _normalize_code_filter(code_filter)
    if normalized_filter is None:
        return len(_qfq_csv_paths(source))
    count = 0
    for path in _qfq_csv_paths(source):
        frame = pd.read_csv(path, dtype={"code": str}, usecols=["code"])
        if frame["code"].astype(str).str.strip().str.zfill(6).isin(normalized_filter).any():
            count += 1
    return count


def iter_qfq_csv_bars(
    source: Path,
    start: pd.Timestamp,
    end: pd.Timestamp,
    progress_callback: ProgressCallback | None = None,
    code_filter: Collection[str] | None = None,
) -> Iterator[pd.DataFrame]:
    """Yield normalized frames from qfq CSV output generated by qfq_run."""
    warmup_start = start - pd.offsets.BDay(180)
    normalized_filter = _normalize_code_filter(code_filter)
    scanned_count = 0
    yielded_count = 0
    required_columns = {"date", "code", "open", "high", "low", "close", "qfq_open", "qfq_high", "qfq_low", "qfq_close"}
    for path in _qfq_csv_paths(source):
        scanned_count += 1
        frame = pd.read_csv(path, dtype={"code": str})
        missing = required_columns - set(frame.columns)
        if missing:
            raise ValueError(f"{path} missing qfq CSV columns: {', '.join(sorted(missing))}")
        if "volume" not in frame.columns:
            if "vol" not in frame.columns:
                raise ValueError(f"{path} missing qfq CSV columns: volume or vol")
            frame["volume"] = frame["vol"]
        frame["code"] = frame["code"].astype(str).str.strip().str.zfill(6)
        if normalized_filter is not None:
            frame = frame.loc[frame["code"].isin(normalized_filter)].copy()
        if frame.empty:
            if progress_callback is not None:
                progress_callback(scanned_count, yielded_count)
            continue
        for raw_column in ("open", "high", "low", "close"):
            frame[f"raw_{raw_column}"] = pd.to_numeric(frame[raw_column], errors="raise")
            frame[raw_column] = pd.to_numeric(frame[f"qfq_{raw_column}"], errors="raise")
        frame = frame.assign(
            name=lambda data: data["code"],
            market_cap=0,
            is_st=False,
            is_suspended=False,
        )
        bars = normalize_daily_bars(frame, require_core_pool=False)
        for _, code_bars in bars.groupby("code", sort=True):
            window = code_bars.loc[code_bars["date"].between(warmup_start, end)].copy()
            if window.empty:
                continue
            yielded_count += 1
            yield window.reset_index(drop=True)
        if progress_callback is not None:
            progress_callback(scanned_count, yielded_count)


def collect_signal_events(
    source_root: Path,
    config: dict[str, object],
    progress_callback: ProgressCallback | None = None,
    code_filter: Collection[str] | None = None,
) -> tuple[pd.DataFrame, dict[str, object]]:
    """Measure frozen signal events one code at a time and retain no daily-bar universe."""
    start, end = pd.Timestamp(config["analysis_start"]), pd.Timestamp(config["analysis_end"])
    event_frames: list[pd.DataFrame] = []
    processed_code_count = 0
    for bars in iter_tdx_mainboard_bars(source_root, start, end, progress_callback=progress_callback, code_filter=code_filter):
        processed_code_count += 1
        signals = build_signal_variants(bars, config)
        for variant in config["variants"]:
            for horizon in config["horizons"]:
                event_frames.append(measure_events(signals, str(variant), int(horizon), config))
    events = pd.concat(event_frames, ignore_index=True) if event_frames else pd.DataFrame(columns=EVENT_COLUMNS)
    if not events.empty:
        events = events.loc[events["signal_date"].between(start, end)].reset_index(drop=True)
    return events, {"processed_code_count": processed_code_count, "data_scope_label": "technical_only_no_historical_market_cap_or_st"}


def collect_control_events(
    source_root: Path,
    config: dict[str, object],
    signal_dates: dict[tuple[str, int], set[pd.Timestamp]],
    progress_callback: ProgressCallback | None = None,
    code_filter: Collection[str] | None = None,
) -> pd.DataFrame:
    """Collect same-date non-signal candidates in a second, per-code pass."""
    if not signal_dates:
        return pd.DataFrame(columns=EVENT_COLUMNS)
    start, end = pd.Timestamp(config["analysis_start"]), pd.Timestamp(config["analysis_end"])
    candidates: list[pd.DataFrame] = []
    for bars in iter_tdx_mainboard_bars(source_root, start, end, progress_callback=progress_callback, code_filter=code_filter):
        signals = build_signal_variants(bars, config)
        for (variant, horizon), dates in signal_dates.items():
            trigger = f"{variant}_first_trigger"
            candidate_dates = signals["date"].isin(dates) & ~signals[trigger]
            if not candidate_dates.any():
                continue
            candidate_signals = signals.copy()
            candidate_signals[trigger] = candidate_dates
            measured = measure_events(candidate_signals, variant, horizon, config)
            if not measured.empty:
                candidates.append(measured.loc[measured["signal_date"].isin(dates)])
    return pd.concat(candidates, ignore_index=True) if candidates else pd.DataFrame(columns=EVENT_COLUMNS)


def sample_control_distribution(
    observed_events: pd.DataFrame, candidate_events: pd.DataFrame, iterations: int, random_seed: int
) -> pd.DataFrame:
    """Sample same-date candidate returns with the observed event count per group."""
    rng = np.random.default_rng(random_seed)
    observed = observed_events.loc[observed_events["status"].eq("filled")]
    candidates = candidate_events.loc[candidate_events["status"].eq("filled")]
    candidate_pools = {
        key: group["net_return"].to_numpy()
        for key, group in candidates.groupby(["variant", "horizon", "signal_date"], sort=True)
    }
    rows = []
    for (variant, horizon), variant_events in observed.groupby(["variant", "horizon"], sort=True):
        date_groups = [(signal_date, len(group)) for signal_date, group in variant_events.groupby("signal_date", sort=True)]
        for iteration in range(iterations):
            sampled_returns = []
            for signal_date, event_count in date_groups:
                pool = candidate_pools.get((variant, horizon, signal_date))
                if pool is None or len(pool) < event_count:
                    continue
                sampled_returns.extend(rng.choice(pool, size=event_count, replace=False))
            rows.append(
                {
                    "variant": variant,
                    "horizon": horizon,
                    "iteration": iteration,
                    "control_mean_return": float(np.mean(sampled_returns)) if sampled_returns else np.nan,
                }
            )
    return pd.DataFrame(rows, columns=["variant", "horizon", "iteration", "control_mean_return"])
